esphome:
  name: tcl-ac
  includes:
    - tcl_climate.h

esp8266:
  board: esp07

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:

ota:
  password: 123

uart:
  id: uart_bus
  tx_pin: 1
  rx_pin: 3
  baud_rate: 9600
  parity: EVEN

logger:
  level: VERBOSE
  baud_rate: 0

climate:
- platform: custom
  lambda: |-
    auto my_custom_climate = new MyCustomClimate(id(uart_bus));
    App.register_component(my_custom_climate);
    return {my_custom_climate};

  climates:
    - name: "TCL a/c"
      id: my_custom_climate

select:
  - platform: template
    name: Vertical swing
    id: vswing
    entity_category: config
    options:
      - "Last position"
      - "Fix top"
      - "Fix upper"
      - "Fix mid"
      - "Fix lower"
      - "Fix bottom"
      - "Move full"
      - "Move upper"
      - "Move lower"
    set_action:
      then:
        lambda: |-
          static_cast<MyCustomClimate*>(id(my_custom_climate))->control_vertical_swing(x);

  - platform: template
    name: Horizontal swing
    id: hswing
    entity_category: config
    options:
      - "Last position"
      - "Fix left"
      - "Fix mid left"
      - "Fix mid"
      - "Fix mid right"
      - "Fix right"
      - "Move full"
      - "Move left"
      - "Move mid"
      - "Move right"
    set_action:
      then:
        lambda: |-
          static_cast<MyCustomClimate*>(id(my_custom_climate))->control_horizontal_swing(x);
